/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.BeneficioDAO;
import java.awt.FontMetrics;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Beneficio;
import table.BeneficioColumnModel;
import table.BeneficioTableModel;
import table.CursoColumnModel;

/**
 *
 * @author Acerpc
 */
public class DlgConsultarBeneficio extends javax.swing.JDialog {

    /**
     * Creates new form DlgConsultarBeneficio
     */
    
    public DlgConsultarBeneficio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (listaBeneficios != null) {
            atualizarTabela();
        }
    }
    
    BeneficioDAO beneficioDAO = new BeneficioDAO();
    List<Beneficio> listaBeneficios = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBeneficio = new javax.swing.JTable();
        buttonEnviar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableBeneficio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBeneficio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBeneficioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBeneficio);

        buttonEnviar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Enviar.png"))); // NOI18N
        buttonEnviar.setText("Enviar");
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarActionPerformed(evt);
            }
        });

        buttonVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Voltar.png"))); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonVoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEnviar)
                    .addComponent(buttonVoltar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        this.dispose();
        new DlgGerenciadorBeneficio(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarActionPerformed
        if (tableBeneficio.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um benefício.");
        } else {
            int linhaSelecionada = this.tableBeneficio.getSelectedRow();
            int id = Integer.parseInt(this.tableBeneficio.getValueAt(linhaSelecionada, 0).toString());
            DlgGerenciadorBeneficio jb = new DlgGerenciadorBeneficio(null, true);
            jb.recuperarDados(id);
            this.dispose();
            jb.setVisible(true);
        }
    }//GEN-LAST:event_buttonEnviarActionPerformed

    private void tableBeneficioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBeneficioMouseClicked
        if (evt.getClickCount() == 2) {
                int linhaSelecionada = this.tableBeneficio.getSelectedRow();
                int idBeneficio = (int) this.tableBeneficio.getValueAt(linhaSelecionada, 0);
                DlgGerenciadorBeneficio bene = new DlgGerenciadorBeneficio(null, true);
                bene.recuperarDados(idBeneficio);
                this.dispose();
                bene.setVisible(true);
        }
    }//GEN-LAST:event_tableBeneficioMouseClicked

    public void atualizarTabela() {
        try {
            listaBeneficios = beneficioDAO.recuperarTodos();
            if (listaBeneficios != null) {
                tableBeneficio.setModel(new BeneficioTableModel(listaBeneficios));
                FontMetrics fm = tableBeneficio.getFontMetrics(tableBeneficio.getFont());
                tableBeneficio.setColumnModel(new BeneficioColumnModel(fm));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DlgConsultarBeneficio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void desativarBotaoETabela (boolean status) {
        buttonVoltar.setEnabled(status);
        buttonEnviar.setEnabled(status);
        tableBeneficio.setEnabled(status);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgConsultarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgConsultarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgConsultarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgConsultarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgConsultarBeneficio dialog = new DlgConsultarBeneficio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnviar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBeneficio;
    // End of variables declaration//GEN-END:variables
}
