/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

import form.login.FrmLogin;

/**
 *
 * @author Aluno
 */
public class DlgMenuConsultas extends javax.swing.JDialog {

    /**
     * Creates new form DlgMenuConsultas
     * @param parent
     * @param modal
     */
    public DlgMenuConsultas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    int nivelUsuario;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btConsultarCurso = new javax.swing.JButton();
        btConsultarOrientador = new javax.swing.JButton();
        btConsultarSupervisor = new javax.swing.JButton();
        btConsultarProfessor = new javax.swing.JButton();
        btConsultarAluno = new javax.swing.JButton();
        btConsultarTurma = new javax.swing.JButton();
        btConsultarBeneficio = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu De Consultas");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 2));
        jPanel1.setLayout(new java.awt.GridLayout(8, 0));

        btConsultarCurso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Curso.png"))); // NOI18N
        btConsultarCurso.setText("Consultar Curso");
        btConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarCursoActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultarCurso);

        btConsultarOrientador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarOrientador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Orientador.png"))); // NOI18N
        btConsultarOrientador.setText("Consultar Orientador");
        btConsultarOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarOrientadorActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultarOrientador);

        btConsultarSupervisor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarSupervisor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Supervisor.png"))); // NOI18N
        btConsultarSupervisor.setText("Consultar Supervisor");
        btConsultarSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSupervisorActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultarSupervisor);

        btConsultarProfessor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Professor.png"))); // NOI18N
        btConsultarProfessor.setText("Consultar Professor");
        btConsultarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarProfessorActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultarProfessor);

        btConsultarAluno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/aluno.png"))); // NOI18N
        btConsultarAluno.setText("Consultar Aluno");
        btConsultarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarAlunoActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultarAluno);

        btConsultarTurma.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Turma.png"))); // NOI18N
        btConsultarTurma.setText(" Consultar Turma ");
        btConsultarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarTurmaActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultarTurma);

        btConsultarBeneficio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cofrinho-Beneficio-Cifrao.png"))); // NOI18N
        btConsultarBeneficio.setText("Consultar Benefício    ");
        btConsultarBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarBeneficioActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultarBeneficio);

        btLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Sair.png"))); // NOI18N
        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btLogout);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LogoIfsc.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarCursoActionPerformed
        this.dispose();
        DlgConsultarCurso consulta = new DlgConsultarCurso(null, true);
        consulta.verificarNivel(nivelUsuario);
        consulta.setVisible(true);
    }//GEN-LAST:event_btConsultarCursoActionPerformed

    private void btConsultarOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarOrientadorActionPerformed
        this.dispose();
        DlgConsultarOrientador telaConsulta = new DlgConsultarOrientador(null, true);
        telaConsulta.verificarNivel(nivelUsuario);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_btConsultarOrientadorActionPerformed

    private void btConsultarSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSupervisorActionPerformed
        this.setVisible(false);
        DlgConsultarSupervisor telaConsulta = new DlgConsultarSupervisor(null, true);
        telaConsulta.verificarNivel(nivelUsuario);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_btConsultarSupervisorActionPerformed

    private void btConsultarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarProfessorActionPerformed
        this.dispose();
        DlgConsultarProfessor telaConsulta = new DlgConsultarProfessor(null, true);
        telaConsulta.verificarNivel(nivelUsuario);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_btConsultarProfessorActionPerformed

    private void btConsultarBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarBeneficioActionPerformed
        this.dispose();
        DlgConsultarBeneficio beneficio = new DlgConsultarBeneficio(null, true);
        beneficio.verificarNivel(nivelUsuario);
        beneficio.setVisible(true);
    }//GEN-LAST:event_btConsultarBeneficioActionPerformed

    private void btConsultarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarTurmaActionPerformed
        this.dispose();
        DlgConsultarTurma consultarTurma = new DlgConsultarTurma(null, true);
        consultarTurma.verificarNivel(nivelUsuario);
        consultarTurma.setVisible(true);
    }//GEN-LAST:event_btConsultarTurmaActionPerformed

    private void btConsultarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarAlunoActionPerformed
        this.dispose();
        DlgConsultarAluno consultarAluno = new DlgConsultarAluno(null, rootPaneCheckingEnabled);
        consultarAluno.verificarNivel(nivelUsuario);
        consultarAluno.setVisible(true);
    }//GEN-LAST:event_btConsultarAlunoActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        this.dispose();
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_btLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgMenuConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgMenuConsultas dialog = new DlgMenuConsultas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarAluno;
    private javax.swing.JButton btConsultarBeneficio;
    private javax.swing.JButton btConsultarCurso;
    private javax.swing.JButton btConsultarOrientador;
    private javax.swing.JButton btConsultarProfessor;
    private javax.swing.JButton btConsultarSupervisor;
    private javax.swing.JButton btConsultarTurma;
    private javax.swing.JButton btLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLogo;
    // End of variables declaration//GEN-END:variables

    public void verificarNivel (int nivel) {
        this.nivelUsuario = nivel;
        if(nivel != 3) {
            btLogout.setEnabled(false);
        }
    }
}
