/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

import form.login.FrmLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class DlgMenuConsultas extends javax.swing.JDialog {

    /**
     * Creates new form DlgMenuConsultas
     * @param parent
     * @param modal
     */
    public DlgMenuConsultas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    int nivelUsuario;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btConsultarCurso = new javax.swing.JButton();
        btConsultarOrientador = new javax.swing.JButton();
        btConsultarSupervisor = new javax.swing.JButton();
        btConsultarProfessor = new javax.swing.JButton();
        btConsultarAluno = new javax.swing.JButton();
        btConsultarTurma = new javax.swing.JButton();
        btConsultarPagamento = new javax.swing.JButton();
        btConsultarBeneficio = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu De Consultas");

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LogoIfsc.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 2));

        btConsultarCurso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Curso.png"))); // NOI18N
        btConsultarCurso.setText("Consultar Curso");
        btConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarCursoActionPerformed(evt);
            }
        });

        btConsultarOrientador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarOrientador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Orientador.png"))); // NOI18N
        btConsultarOrientador.setText("Consultar Orientador");
        btConsultarOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarOrientadorActionPerformed(evt);
            }
        });

        btConsultarSupervisor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarSupervisor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Supervisor.png"))); // NOI18N
        btConsultarSupervisor.setText("Consultar Supervisor");
        btConsultarSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSupervisorActionPerformed(evt);
            }
        });

        btConsultarProfessor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Professor.png"))); // NOI18N
        btConsultarProfessor.setText("Consultar Professor");
        btConsultarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarProfessorActionPerformed(evt);
            }
        });

        btConsultarAluno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/aluno.png"))); // NOI18N
        btConsultarAluno.setText("Consultar Aluno");
        btConsultarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarAlunoActionPerformed(evt);
            }
        });

        btConsultarTurma.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Turma.png"))); // NOI18N
        btConsultarTurma.setText(" Consultar Turma ");
        btConsultarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarTurmaActionPerformed(evt);
            }
        });

        btConsultarPagamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pagamento.png"))); // NOI18N
        btConsultarPagamento.setText("Consultar Pagamento");
        btConsultarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarPagamentoActionPerformed(evt);
            }
        });

        btConsultarBeneficio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConsultarBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cofrinho-Beneficio-Cifrao.png"))); // NOI18N
        btConsultarBeneficio.setText("Consultar Benefício    ");
        btConsultarBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarBeneficioActionPerformed(evt);
            }
        });

        btLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Sair.png"))); // NOI18N
        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConsultarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultarOrientador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultarSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultarTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultarBeneficio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultarPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btConsultarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btConsultarOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarBeneficio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLogout))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarCursoActionPerformed
        this.dispose();
        DlgConsultarCurso consulta = new DlgConsultarCurso(null, true);
        consulta.verificarNivel(nivelUsuario);
        consulta.setVisible(true);
    }//GEN-LAST:event_btConsultarCursoActionPerformed

    private void btConsultarOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarOrientadorActionPerformed
        this.dispose();
        DlgConsultarOrientador telaConsulta = new DlgConsultarOrientador(null, true);
        telaConsulta.verificarNivel(nivelUsuario);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_btConsultarOrientadorActionPerformed

    private void btConsultarSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSupervisorActionPerformed
        this.setVisible(false);
        DlgConsultarSupervisor telaConsulta = new DlgConsultarSupervisor(null, true);
        telaConsulta.verificarNivel(nivelUsuario);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_btConsultarSupervisorActionPerformed

    private void btConsultarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarProfessorActionPerformed
        this.dispose();
        DlgConsultarProfessor telaConsulta = new DlgConsultarProfessor(null, true);
        telaConsulta.verificarNivel(nivelUsuario);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_btConsultarProfessorActionPerformed

    private void btConsultarBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarBeneficioActionPerformed
        this.dispose();
        DlgConsultarBeneficio beneficio = new DlgConsultarBeneficio(null, true);
        beneficio.verificarNivel(nivelUsuario);
        beneficio.setVisible(true);
    }//GEN-LAST:event_btConsultarBeneficioActionPerformed

    private void btConsultarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarTurmaActionPerformed
        this.dispose();
        DlgConsultarTurma consultarTurma = new DlgConsultarTurma(null, true);
        consultarTurma.verificarNivel(nivelUsuario);
        consultarTurma.setVisible(true);
    }//GEN-LAST:event_btConsultarTurmaActionPerformed

    private void btConsultarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarAlunoActionPerformed
        this.dispose();
        DlgConsultarAluno consultarAluno = new DlgConsultarAluno(null, rootPaneCheckingEnabled);
        consultarAluno.verificarNivel(nivelUsuario);
        consultarAluno.setVisible(true);
    }//GEN-LAST:event_btConsultarAlunoActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja sair?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (resposta == 0) {
            new FrmLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btConsultarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarPagamentoActionPerformed
        this.dispose();
        DlgConsultarPagamento consultarPagamento = new DlgConsultarPagamento();
        //consultarPagamento.verificarNivel(nivelUsuario);
        consultarPagamento.setVisible(true);
    }//GEN-LAST:event_btConsultarPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgMenuConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgMenuConsultas dialog = new DlgMenuConsultas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarAluno;
    private javax.swing.JButton btConsultarBeneficio;
    private javax.swing.JButton btConsultarCurso;
    private javax.swing.JButton btConsultarOrientador;
    private javax.swing.JButton btConsultarPagamento;
    private javax.swing.JButton btConsultarProfessor;
    private javax.swing.JButton btConsultarSupervisor;
    private javax.swing.JButton btConsultarTurma;
    private javax.swing.JButton btLogout;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbLogo;
    // End of variables declaration//GEN-END:variables

    public void verificarNivel (int nivel) {
        this.nivelUsuario = nivel;
        if(nivel != 3) {
            btLogout.setEnabled(false);
        }
    }
}
